### ISSUE TITLE
Increase the amount of outposts a town gets

### ISSUE THREAD

**Issue by aco4** [rDankMemes/Minecraft-Server-Support#69]
**Is your feature request related to a problem? Please describe.**
It is frustrating not being able to claim an area because you don't have enough outposts. You can get more by having more residents, but the number of residents is too high. For example, DC has 36 residents but only 3 outposts.
```
town_level:
  - numResidents: 0
    townOutpostLimit: 0
  - numResidents: 1
    townOutpostLimit: 1
  - numResidents: 10
    townOutpostLimit: 2
  - numResidents: 30
    townOutpostLimit: 3
  - numResidents: 50
    townOutpostLimit: 5
  - numResidents: 75
    townOutpostLimit: 7
  - numResidents: 100
    townOutpostLimit: 10
```

**Describe the solution you'd like**
Increase the amount of outposts given.
```
town_level:
  - numResidents: 0
    townOutpostLimit: 0
  - numResidents: 1
    townOutpostLimit: 3
  - numResidents: 10
    townOutpostLimit: 6
  - numResidents: 20
    townOutpostLimit: 9
  - numResidents: 30
    townOutpostLimit: 12
  - numResidents: 40
    townOutpostLimit: 15
  - numResidents: 50
    townOutpostLimit: 18
  - numResidents: 75
    townOutpostLimit: 20
```

**Describe alternatives you've considered**
none

**Additional context**
none
